language: node_js
node_js:
  - 10
env:
  global:
    - CONST_DATA=123
branches:
  only:
    - master
install:
  - npm install
script:
  - echo "branch is $TRAVIS_BRANCH, commit id is $TRAVIS_COMMIT"
  - rm -rf './dist'
  - npm run build
  - cd ./dist
  - git init
  - git checkout -b gh-pages
  - git add .
  - git commit -m 'travis update file'
  - git push "https://$GITHUB_TOKEN@github.com/pujianguo/travis_vue.git" gh-pages:gh-pages -f
  - echo https://pujianguo.github.io/travis_vue
after_success:
  - echo 'success'
